language: node_js

node_js:
  - "6"
  - "7"

notifications:
  email: false

script:
  - npm run travis

after_success:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
  